### ISSUE TITLE
Open to patches? (Add tests)

### ISSUE THREAD

**Issue by Ironholds** [aboruvka/coxinterval#2]
I'd like to make some patches to make the code more readable and use roxygen2 for documentation. Would that be okay?

**Comment by aboruvka** [comment]
Pull requests are welcome, but I am unsure about this case - my interest in adopting roxygen2 is pretty low. Were there other changes you had in mind?

**Comment by Ironholds** [comment]
Linebreaks in the code to make it more readable to future patchers, plus the introduction of some rudimentary unit tests, if that'd be okay?

**Comment by aboruvka** [comment]
For the tests, I can have a look if you submit a pull request. Location of line breaks (here just line feeds - different from DOS/Windows line endings) are a matter of preference, and I'd prefer to leave as-is. 

I should warn you though that my priorities right now are still focused on package use (model syntax, new features) rather than making the source code more readable.

**Comment by Ironholds** [comment]
Fair point! Thinking on it I'll probably just finish off a couple of my packages, then - if you're still building out new features and not looking at the architecture I can come back when you are :)

**Comment by aboruvka** [comment]
Up to you. I can convert the documentation examples into formal tests in the next release. Thanks for the suggestion. For the line breaks, you'll need to view the source with an editor that will break at line feeds. I don't develop in Windows.
